main: fr.atlasworld.daedalus.bukkit.plugin.DaedalusTestPlugin
name: DaedalusTestPlugin
version: 1.0.0
api-version: 1.20
depend: [creative-central]
commands:
    daedalus:
        description: Main command for daedalus-engine test plugin